spring:
    datasource:
        password: Data99kbs!addy
        url: jdbc:mysql://localhost:3306/oams-test?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDB
